# Generated by Django 5.0.6 on 2024-05-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PizzaName', models.CharField(max_length=20)),
                ('PizzapriceM', models.DecimalField(decimal_places=2, max_digits=4)),
                ('PizzapriceL', models.DecimalField(decimal_places=2, max_digits=4)),
                ('PizzaImage', models.URLField()),
            ],
        ),
    ]
