# Generated by Django 5.0.6 on 2024-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamodel',
            name='PizzapriceL',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='PizzapriceM',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
