# Generated by Django 5.0.6 on 2024-05-11 21:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0004_order_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemModel',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderModel',
        ),
    ]
